# Generated by Django 3.1.8 on 2021-04-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('user_profile', '0005_auto_20210419_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_question',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.question'),
        ),
    ]
