# Generated by Django 3.1.8 on 2021-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
