# Generated by Django 3.1.8 on 2021-04-20 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20210420_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_submission',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
