# Generated by Django 3.1.8 on 2021-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Fail')], default=1),
        ),
    ]
