# Generated by Django 3.1.8 on 2021-04-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_auto_20210420_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Correct Answer'), (2, 'Wrong Answer')], default=1),
        ),
    ]
