# Generated by Django 3.1.8 on 2021-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0003_response_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Correct Answer'), (0, 'Wrong Answer')], default=1),
        ),
    ]
